[book]
language = "en"
src = "docs"
title = "Target Intermediate Representation"

[build]
create-missing = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
